# Generated by Django 4.2.7 on 2024-01-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True, verbose_name='Event Name')),
                ('event_date', models.DateTimeField(null=True, verbose_name='Event Date')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_tags', models.CharField(default='Post', max_length=255)),
                ('body', models.TextField()),
                ('main_photo', models.ImageField(blank=True, default='uploads/OIP.jpg', null=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Venue Name')),
                ('address', models.CharField(blank=True, max_length=120)),
                ('zip_code', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(max_length=10, verbose_name='Phone')),
                ('web', models.URLField(blank=True, verbose_name='URL Adress')),
                ('email_adress', models.EmailField(max_length=120, verbose_name='Email')),
            ],
        ),
    ]
