# Generated by Django 4.2.7 on 2024-03-03 14:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_venue_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='employees',
            field=models.ManyToManyField(blank=True, null=True, related_name='Employees', to=settings.AUTH_USER_MODEL),
        ),
    ]
