# Generated by Django 4.2.7 on 2024-03-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_remove_profile_venue'),
        ('events', '0005_venue_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='employees',
            field=models.ManyToManyField(blank=True, null=True, related_name='Employees', to='members.profile'),
        ),
    ]
