# Generated by Django 4.2.7 on 2024-01-22 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('team_short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('web_page', models.URLField(blank=True, max_length=255, null=True)),
                ('facebook_page', models.URLField(blank=True, max_length=255, null=True)),
                ('istagram_page', models.URLField(blank=True, max_length=255, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('main_photo', models.ImageField(blank=True, default='uploads/OIP.jpg', null=True, upload_to='clubs_main_photo/')),
                ('club_admin', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('photo_profile', models.ImageField(blank=True, default='uploads/OIP.jpg', null=True, upload_to='user_photo_profile/')),
                ('club_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.club')),
            ],
        ),
    ]
