# Generated by Django 4.2.7 on 2024-01-21 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userapp',
            options={'managed': False},
        ),
    ]
