# Generated by Django 4.2.7 on 2024-01-21 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_userapp_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userapp',
            options={},
        ),
    ]
