# Generated by Django 4.2.7 on 2024-01-26 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_club_club_members_alter_club_club_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='club_id',
            new_name='club',
        ),
    ]
