# Generated by Django 4.2.7 on 2024-01-21 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('members', '0003_alter_userapp_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('photo_profile', models.ImageField(blank=True, default='uploads/OIP.jpg', null=True, upload_to='user_photo_profile/')),
            ],
        ),
        migrations.RemoveField(
            model_name='userapp',
            name='club_id',
        ),
        migrations.RemoveField(
            model_name='userapp',
            name='user',
        ),
    ]
