# Generated by Django 4.2.7 on 2024-01-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_club_id_profile_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='club_profile_status',
            field=models.CharField(blank=True, choices=[('New user', 'New user'), ('New club member', 'New club member'), ('Profile change', 'Profile change'), ('Confirmed profile', 'Confirmed profile')], default='New user', max_length=100, null=True),
        ),
    ]
