# Generated by Django 4.2.7 on 2024-01-21 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_profile_remove_userapp_club_id_remove_userapp_user'),
        ('events', '0002_alter_event_attendees_alter_event_manager_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserApp',
        ),
        migrations.AddField(
            model_name='profile',
            name='club_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.club'),
        ),
    ]
