# Generated by Django 4.2.7 on 2024-01-31 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_clubiceopenhours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubiceopenhours',
            options={'ordering': ('weekday', 'from_hour'), 'verbose_name_plural': 'Club Ice Open Hours'},
        ),
    ]
