# Generated by Django 4.2.7 on 2024-02-10 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_host_club'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0010_alter_clubiceopenhours_weekday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=25, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('from_hour', models.DateTimeField()),
                ('to_hour', models.DateTimeField()),
                ('attendees', models.ManyToManyField(blank=True, null=True, related_name='attendees', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Reservation_club', to='members.club')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Reservation_venue', to='events.venue')),
            ],
        ),
    ]
