# Generated by Django 4.2.7 on 2024-02-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='from_hour',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='to_hour',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
