# Generated by Django 4.2.7 on 2024-02-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_alter_reservation_from_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='month',
            field=models.CharField(choices=[('1', 'Waiting for confirmation'), ('2', 'Confirmed'), ('3', 'Canceled'), ('4', 'Settled')], default='1', max_length=2),
        ),
    ]
