# Generated by Django 4.2.7 on 2024-02-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_profile_venue_alter_venueiceopenhours_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='from_hour',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='to_hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
