# Generated by Django 4.2.7 on 2024-02-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_reservation_reservation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='from_hour',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='to_hour',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
