# Generated by Django 4.2.7 on 2024-02-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_venuetrack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='club',
        ),
    ]
