# Generated by Django 4.2.7 on 2024-02-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_remove_reservation_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuetrack',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='venuetrack',
            name='note',
            field=models.CharField(blank=True, default='Track 1', max_length=10, null=True),
        ),
    ]
