# Generated by Django 4.2.7 on 2024-02-25 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_alter_venuetrack_id_alter_venuetrack_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venuetrack',
            old_name='note',
            new_name='title',
        ),
    ]
