# Generated by Django 4.2.7 on 2024-02-25 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_rename_note_venuetrack_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='track',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Reservation_track', to='members.venuetrack'),
        ),
    ]
