# Generated by Django 4.2.7 on 2024-03-03 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_reservation_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='venue',
        ),
    ]
