# Generated by Django 4.2.7 on 2024-03-25 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_profile_venue_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='month',
            new_name='status',
        ),
    ]
