# Generated by Django 4.2.7 on 2024-04-07 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0026_profile_friends_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='attendees',
            field=models.ManyToManyField(blank=True, null=True, related_name='attendees_reservation', to='members.profile'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
