# Generated by Django 4.2.7 on 2024-04-07 16:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0027_alter_reservation_attendees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='attendees',
            field=models.ManyToManyField(blank=True, null=True, related_name='attendees_reservation', to=settings.AUTH_USER_MODEL),
        ),
    ]
